# application
spring:
  application:
    name: drm_opentosca_mock
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# server
server:
  port: 8080

# logging
logging:
  level:
    drm.opentosca.mock: trace